# Este archivo define la configuraci칩n para semantic-release.
# Solo incluimos plugins de an치lisis y Git para evitar el error ENOPKG.
plugins:
  # Analiza commits para determinar el tipo de versi칩n (major, minor, patch)
  - "@semantic-release/commit-analyzer"
  # Genera las notas de lanzamiento
  - "@semantic-release/release-notes-generator"
  # Gestiona el archivo CHANGELOG.md
  - "@semantic-release/changelog"
  # Gestiona la creaci칩n de tags de Git y la subida de archivos (incluyendo CHANGELOG.md)
  - "@semantic-release/git"
